config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, :templates, :actors
  resources :sessions, :only => [:new, :create, :destroy]
  root to: 'templates#index'

  get '/signup' => 'users#new'
  get '/logout' => 'sessions#destroy'
  get '/login' => 'sessions#new'
  post '/users' => 'users#create'

  post '/create_monster', to: 'templates#create_monster', as: 'create_monster'
  post '/favorite', to: 'templates#favorite', as: 'favorite'
  post '/unfavorite', to: 'templates#unfavorite', as: 'unfavorite'
  patch '/damage', to: 'actors#damage', as: 'damage'

end

app/views/templates/_templates.html.erb
<div class="card border-primary mb-3 col-md-4" style="width:300px;">

  <div class="card-header">
    <h4 class="card-title"><%=template.name%> </h4>
    <h5 class="card-subtitle mb-2 text-muted">Lv: <%=template.challenge%></h5>
  </div>

  <div class = "card-body">

    <% if template.image %>
      <%= image_tag(template.image.url(:med), class:'card-img-top;center')%>
    <% else %>
      <img src="public/404.gif" height=256px height=256px alt="image not found">
    <% end %>
    <h5>HP: <%= template.hp_s %></h5>
    <h5>AC: <%=template.ac_s%></h5>

    <% if current_user %>
      <ul>
          <% if !current_user.templates.exists?(template.id) %>
            <li><%= button_to "Favourite", favorite_path, method: :post, :class =>"btn btn-primary", params: { user: current_user, template: template } %></li>
          <% else %>
            <li><%= button_to "Unfavourite", unfavorite_path, method: :post, :class =>"btn btn-primary", params: { user: current_user, template: template } %></li>
          <% end %>
        <li><%= link_to "Inspect", template, :class =>"btn btn-primary" %></li>
        <li><%= link_to "Delete", template, method: :delete, :class =>"btn btn-primary" %></li>
        <li><%= button_to "Spawn", create_monster_path, class:"btn btn-primary", params: { user: current_user, template: template} %></li>
      </ul>
    <% end %>
  </div>
</div>

app/views/templates/index.html.erb
<h1> Monster Templates</h1>

  <% if current_user%>
    <div>
      <h2>Favourites</h2>
        <div class="container-fluid row" style="width:90%;background-color:white;">
          <% current_user.templates.each do |template|%>
            <%= render partial: 'templates', locals: {template: template}%>
          <% end %>
        </div>
    <div>
  <% end %>

  <div>
    <h2>Catalog</h2>
      <div class="container-fluid row" style="width:90%;background-color:white;">
        <% @templates.each do |template|%>
          <%= render partial: 'templates', locals: {template: template}%>
        <% end %>
      </div>
    </div>
  </div>

app/views/templates/new.html.erb
<!-- app/views/users/new.html.erb -->

<h1>Create a Monsters Template!</h1>
<div class="row col-md-4 col-md-offset-4 control-label ">
<%= form_for :template, html:{multipart: true}, url: '/templates' do |f| %>

  Name: <%= f.text_field :name %>
  Description: <%= f.text_field :desc %>

  HP: <%= f.text_field :hp_s %>
  AC: <%= f.text_field :ac_s %>
  Speed: <%= f.text_field :speed %>

  Str: <%= f.text_field :str_s %>
  Dex: <%= f.text_field :dex_s %>
  Con: <%= f.text_field :con_s %>
  Int: <%= f.text_field :int_s %>
  Wis: <%= f.text_field :wis_s %>
  Cha: <%= f.text_field :cha_s %>

  Saving Throws: <%= f.text_field :saving_throws %>
  Skills: <%= f.text_field :skills %>
  Senses: <%= f.text_field :senses %>
  Abilities: <%= f.text_field :abilities %>
  CR: <%= f.text_field :challenge %>

  Actions: <%= f.text_field :actions %>

  Image: <%= f.file_field :image %>

  <%= f.submit "Submit" %>

<% end %>
</div>

app/views/templates/show.html.erb
<div class="card border-primary mb-3 col-md-4" style="width:600px;">

  <div class="card-header">
    <h4 class="card-title"><%=@template.name%> </h4>
    <h5 class="card-subtitle mb-2 text-muted"><%= @template.desc%>, Lv: <%=@template.challenge%></h5>
  </div>

  <div class = "card-body">

    <%= image_tag(@template.image.url(:large), class:'card-img-top;center')%>

    <div class="row">
      <h5 class="col-md-4">HP: <%= @template.hp_s %></h5>
      <h5 class="col-md-4">AC: <%= @template.ac_s %></h5>
      <h5 class="col-md-4">Speed: <%= @template.speed %></h5>
    </div>

    <div class="row">
      <h5 class="col-md-2">STR: <%= @template.str_s %></h5>
      <h5 class="col-md-2">DEX: <%= @template.dex_s %></h5>
      <h5 class="col-md-2">CON: <%= @template.con_s %></h5>
      <h5 class="col-md-2">INT: <%= @template.int_s %></h5>
      <h5 class="col-md-2">WIS: <%= @template.wis_s %></h5>
      <h5 class="col-md-2">CHA: <%= @template.cha_s %></h5>
    </div>

    <div>
      <h3>Actions</h3>
      <%= @template.actions%>
    </div>

    <div>
      <h3>Saving Throws</h3>
      <%= @template.saving_throws%>
    </div>

    <div class="row">
      
    </div>

    <a href="#" class="btn btn-primary">Favourite</a> <a href="#" class="btn btn-primary">Spawn</a>
  </div>
</div>